### PR TITLE
Fix URL rebasing for LESS files within subdirs.

### PR DESCRIPTION
**Pull request by gauthierm**

### CODE REVIEW

**Comment by nburka** [comment]
I've already merged - but now I see an issue when I try to test your PR. I copied the `less.js` file into `node_modules/sogulp/lib/less.js` and restarted `gulp`, but now I get:

screenshot 2016-01-06 08 06 33

**Comment by gauthierm** [comment]
I think that iss ue was happening beforehand as well.

**Comment by nburka** [comment]
But aren't the first two lines supposed to work with the gulp changes?

**Comment by gauthierm** [comment]
I don't get the first two errors using the updated gulp file.

**Pull request merged**
